name: Java CI with Gradle

on:
  push:
    branches: [ production, development ]
  pull_request:
    branches: [ production, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          REPSY_USERNAME: ${{ secrets.REPSY_USERNAME }}
          REPSY_PASSWORD: ${{ secrets.REPSY_PASSWORD }}
