name: Generate Documentation

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate Documentation
        run: ./gradlew dokkaHtml
        env:
          REPSY_USERNAME: ${{ secrets.REPSY_USERNAME }}
          REPSY_PASSWORD: ${{ secrets.REPSY_PASSWORD }}
      - name: Commit files
        run: |
          git config --local user.name "Github Actions"
          git checkout -b gh-pages origin/gh-pages
          git fetch origin
          git merge
          cp -r ./utils/build/dokka/html/ docs
          touch ./docs/.nojekyll
          git add ./docs/ -f
          git commit -m "Deploy docs from commit" -a
      - name: Push to GitHub
        run: git push -u origin gh-pages:gh-pages
